
pipeline {

  agent any
    
  tools {nodejs "Node-12.18.3"}
    
  stages {
     
    stage('Build') {
      steps {
        sh 'cd AnotherProject'
        sh 'yarn install'
      }
    }  
    
            
    stage('Test') {
      steps {
        sh 'yarn test'
      }
    }
  }
}