
pipeline {

  agent any
    
  tools {nodejs "Node-12.18.3"}
    
  stages {
    
    stage('Git') {
      steps {
        git url: 'https://github.com/AndersonSouzax/food-recipes-mobile.git', branch: 'master'
        sh "ls -lart ./*" 
        sh "git branch -a"
      }
    }

    stage('Build') {
      steps {
        sh 'cd AnotherProject'
        sh 'yarn install'
      }
    }  
    
            
    stage('Test') {
      steps {
        sh 'yarn test'
      }
    }
  }
}